#!/bin/sh
# ShiTTY FETCH & busybox and POSIX compliant
# this file is licensed under the LGPLv2.
# this file was not made by any AI

# i dont know why, but i think a simple fetch shouldn't be so
# over complicated.

# thanks to:
# dylanaraps for the pure-sh-bible
# fastfetch for the logos

# * [JUMP TO ACTUAL FETCH PRINT](#SHPRINT)

supercoolhelp(){
printf "%s" "\
ShiTTY FETCH, a very poopy fetch 💩
usage: shfetch

optional arguments
-h --help		displays this help.
-d	 		enables debugging (prints everything even if empty).
-t --toilet		uses \`toilet -f pagga\` to print the distribution name (can't be spaced).
-C --right [num] 	spaces the table to the right a given number of spaces.
-s --sep [num] 		sets the separation between data:______value

"
exit 0
}
while [ $# -gt 0 ] ; do
    case $1 in
        -d | --debug) debug=1 ; shift ;;
        -h | --h*)  supercoolhelp ;;
        -t | --toilet) toilet=1 ; shift ;;
        -C | --right) space=${2} ; shift 2 ;;
        -s | --sep*) separ=${2} ; shift 2 ;;
        *) printf "ermmmmm, idk what you're talking about,\nyour arguments are kinda strange.\n" ; shift ; exit 2 ;;
    esac
    shift
done
space=${space:-1}
separ=${separ:-16}

# table initialization
# --------------------
distro=$(grep ^PRETTY_NAME /etc/os-release)
	# remove from left(##) 		  ; remove from right(%%)
	# keep one \", for parsing only the distro name to embtoilet
    distro=${distro#PRETTY_NAME=}; distro=${distro%\'}
[ -e /sys/devices/virtual/dmi/id/product_name ] && host=$(cat /sys/devices/virtual/dmi/id/product_name)
kernel=$(uname -r)
uptime=$(uptime)
    uptime=${uptime%%user*} ; uptime=${uptime%,*} ; uptime=${uptime##*"up "} ; uptime=$(echo $uptime | sed  's/:/h/')
# pkgs and colors
    case "$distro" in
       *Gentoo*) pkgs="$(qlist -I | wc -l) (emerge)" ; c0="\033[10;35m" ; c1="\033[10;95m" ; clogo="" ;;
       # comment: gnu `grep` is much faster than busybox `grep`
       *Alpine*) pkgs="$(grep ^C:Q /lib/apk/db/installed | wc -l) (apk)" ;  c0="\033[2;34m" ; c1="\033[2;36m" ; clogo="" ;
    esac
clr="\033[0m"

shell=$SHELL
disp=${WAYLAND_DISPLAY%%-*}
    # Check if its xorg
    if [ -z "$disp" ] && [ "$DISPLAY" = ":0" ]; then disp="xorg" ; fi ;
term=$TERM
cpu="$(grep -m 1 '^model name' /proc/cpuinfo )" ; cpu=${cpu#*:}; [ -z "$cpu" ] && cpu="$(arch)"
				     # delete  kB	     delete spaces and name
tram=$(grep ^MemTotal: /proc/meminfo) ; tram=${tram%\ *} ; tram=${tram##"MemTotal:"*\ }
fram=$(grep ^MemAvailable:  /proc/meminfo) ; fram=${fram%\ *} ; fram=${fram##"MemAvailable:"*\ }
    tram=$(echo "scale=2 ;$tram/1024/1024" | bc -s)
    fram=$(echo "scale=2 ;$fram/1024/1024" | bc -s)     ; uram=$(echo "scale=2 ;$tram-$fram" | bc -s)
    ram="$uram/${tram}GiB"
    unset tram fram uramright
[ -d "/sys/class/power_supply/BAT0" ] && battery="$(cat /sys/class/power_supply/BAT0/capacity)%% [$(cat /sys/class/power_supply/BAT0/status)]"
locale=$LANG

embtoilet() {
# no comments, new lines and stdin cutted for space efficiency
# see https://codeberg.org/melspowr/embtoilet for full version
distro=$1; distro=$(printf "$distro" | tr 'A-Z' 'a-z') ; printf "\n\n\n" ; printf "\033[3A\033[${space}C"
while [ ${#distro} -ne 0 ] ; do i=$(printf "%.1s" "$distro" ) ; distro=${distro#${i}}
case $i in
a)char="░█▀█ ░█▀█ ░▀░▀";;
b)char="░█▀▄ ░█▀▄ ░▀▀░";;
c)char="░█▀▀ ░█░░ ░▀▀▀";;
d)char="░█▀▄ ░█░█ ░▀▀░";;
e)char="░█▀▀ ░█▀▀ ░▀▀▀";;
f)char="░█▀▀ ░█▀▀ ░▀░░";;
g)char="░█▀▀ ░█░█ ░▀▀▀";;
h)char="░█░█ ░█▀█ ░▀░▀";;
i)char="░▀█▀ ░░█░ ░▀▀▀";;
j)char="░▀▀█ ░░░█ ░▀▀░";;
k)char="░█░█ ░█▀▄ ░▀░▀";;
l)char="░█░░ ░█░░ ░▀▀▀";;
m)char="░█▄█ ░█░█ ░▀░▀";;
n)char="░█▀█ ░█░█ ░▀░▀";;
o)char="░█▀█ ░█░█ ░▀▀▀";;
p)char="░█▀█ ░█▀▀ ░▀░░";;
q)char="░▄▀▄ ░█\\█ ░░▀\\";;
r)char="░█▀▄ ░█▀▄ ░▀░▀";;
s)char="░█▀▀ ░▀▀█ ░▀▀▀";;
t)char="░▀█▀ ░░█░ ░░▀░";;
u)char="░█░█ ░█░█ ░▀▀▀";;
v)char="░█░█ ░▀▄▀ ░░▀░";;
w)char="░█░█ ░█▄█ ░▀░▀";;
x)char="░█░█ ░▄▀▄ ░▀░▀";;
y)char="░█░█ ░░█░ ░░▀░";;
z)char="░▀▀█ ░▄▀░ ░▀▀▀";;
1)char="░▀█░ ░░█░ ░▀▀▀";;
2)char="░▀▀▄ ░▄▀░ ░▀▀▀";;
3)char="░▀▀█ ░░▀▄ ░▀▀░";;
4)char="░█░█ ░░▀█ ░░░▀";;
5)char="░█▀▀ ░▀▀▄ ░▀▀░";;
6)char="░▄▀▀ ░█▀▄ ░░▀░";;
7)char="░▀▀█ ░▄▀░ ░▀░░";;
8)char="░▄▀▄ ░▄▀▄ ░░▀░";;
9)char="░▄▀▄ ░░▀█ ░▀▀░";;
0)char="░▄▀▄ ░█/█ ░░▀░";;
.)char="░░░ ░░░ ░▀░";;
,)char="░░░░ ░░░░ ░▄▀░";;
*)char="░░ ░░ ░░";;
esac
for line in $char ; do printf $line ; printf "\033[1B\033[${#line}D" ; done
printf "\033[3A\033[${#line}C"
done ; printf "\033[3B\r"
}

space(){
spc=$space
while [ $spc -gt 0 ]; do
    printf " " ; spc=$(($spc-1))
done
}


#SHPRINT
## table build
## -----------
[ -z "$toilet" ]   && distro=$(embtoilet "${distro#*\'}")
[ ! -z "$toilet" ] && distro="$(toilet -f pagga "${distro#*\'}")\n"
   host="host:           $host"
 kernel="kernel:         $kernel"
 uptime="uptime:         $uptime"
   pkgs="pkgs:           $pkgs"
  shell="shell:          $shell"
   disp="disp:           $disp"
   term="term:           $term"
    cpu="cpu:            $cpu"
    ram="ram:            $ram"
battery="battery:            $battery"
 locale="locale:         $locale"
# --------------------

printf "${clogo}$distro${clr}"
for line in  "$host" "$kernel" "$uptime" "$pkgs" "$shell" "$disp" "$term" "$cpu" "$ram" "$battery" "$locale" ; do
    set $line
   	    # from  https://github.com/dylanaraps/pure-sh-bible#conditional-expressions
   	    # honestly idk why it works
    if [ ! -z "${2#${2%%[![:space:]]*}}" ] || [ $debug ]; then
        space
        printf "${c0}$1${clr}\033[${#1}D" ; shift
        printf "\033[${separ}C${c1}$*${clr}\n"
    fi
done
