#!/bin/sh
# ShiTTY FETCH & busybox and POSIX compliant
# this file is licensed under the LGPLv2.
# this file was not made by any AI

# i dont know why, but i think a simple fetch shouldn't be so
# over complicated.

# thanks to:
# dylanaraps for the pure-sh-bible
# fastfetch for the logos

# table initialization
# --------------------
distro=$(grep PRETTY_NAME /etc/os-release)
	# remove from left(##) 		  ; remove from right(%%)
    distro=${distro##"PRETTY_NAME='"} ; distro=${distro%%\'}
host=$(cat /sys/devices/virtual/dmi/id/product_name)
kernel=$(uname -r)
uptime=$(uptime)
    uptime=${uptime%%","*} ; uptime=${uptime##*"up "} ; uptime=$(echo $uptime | tr ":" "h")
# pkgs (sorry this is the most extense part)
    case "$distro" in
       *Gentoo*) pkgs="$(qlist -I | wc -l) (emerge)"
    esac
shell=$SHELL
disp=${WAYLAND_DISPLAY%%-0}
    # Check if its xorg
    if [ -z $disp ] && [ $DISPLAY = ":0" ]; then disp="xorg" ; fi ;
term=$TERM
cpu=$(uname -p)
gpu=$(lspci)				     # delete  kB	     delete spaces and name
tram=$(grep MemTotal: /proc/meminfo) ; tram=${tram%\ *} ; tram=${tram##"MemTotal:"*\ }
fram=$(grep MemAvailable:  /proc/meminfo) ; fram=${fram%\ *} ; fram=${fram##"MemAvailable:"*\ }
    tram=$(echo "scale=2 ;$tram/1024/1024" | bc -s)
    fram=$(echo "scale=2 ;$fram/1024/1024" | bc -s)     ; uram=$(echo "scale=2 ;$tram-$fram"     | bc -s)
    ram="$uram/$tram GiB"
    unset tram fram uram
battery="$(cat /sys/class/power_supply/BAT0/capacity)%% [$(cat /sys/class/power_supply/BAT0/status)]"
locale=$(locale | grep LANG)
    locale=${locale##"LANG="}
# --------------------

embtoilet() {
    #!/bin/sh
if [ $# -gt 0 ]; then
   distro=$1
else
    read distro
fi
# caps support
distro=$(printf "$distro" | tr 'A-Z' 'a-z')

printf "\n\n\n"
printf "\033[3A"
while [ ${#distro} -ne 0 ] ; do
# get the first character
i=$(printf "%.1s" "$distro" )
#echo $i ; exit 0
#delete the char
distro=${distro#${i}}
    case $i in
a)char='
░█▀█
░█▀█
░▀░▀';;
b)char='
░█▀▄
░█▀▄
░▀▀░';;
c)char='
░█▀▀
░█░░
░▀▀▀';;
d)char='
░█▀▄
░█░█
░▀▀░';;
e)char='
░█▀▀
░█▀▀
░▀▀▀';;
f)char='
░█▀▀
░█▀▀
░▀░░';;
g)char='
░█▀▀
░█░█
░▀▀▀';;
h)char='
░█░█
░█▀█
░▀░▀';;
i)char='
░▀█▀
░░█░
░▀▀▀';;
j)char='
░▀▀█
░░░█
░▀▀░';;
k)char='
░█░█
░█▀▄
░▀░▀';;
l)char='
░█░░
░█░░
░▀▀▀';;
m)char='
░█▄█
░█░█
░▀░▀';;
n)char='
░█▀█
░█░█
░▀░▀';;
o)char='
░█▀█
░█░█
░▀▀▀';;
p)char='
░█▀█
░█▀▀
░▀░░';;
q)char='
░▄▀▄
░█\█
░░▀\';;
r)char='
░█▀▄
░█▀▄
░▀░▀';;
s)char='
░█▀▀
░▀▀█
░▀▀▀';;
t)char='
░▀█▀
░░█░
░░▀░';;
u)char='
░█░█
░█░█
░▀▀▀';;
v)char='
░█░█
░▀▄▀
░░▀░';;
w)char='
░█░█
░█▄█
░▀░▀';;
x)char='
░█░█
░▄▀▄
░▀░▀';;
y)char='
░█░█
░░█░
░░▀░';;
z)char='
░▀▀█
░▄▀░
░▀▀▀';;
1)char='
░▀█░
░░█░
░▀▀▀';;
2)char='
░▀▀▄
░▄▀░
░▀▀▀';;
3)char='
░▀▀█
░░▀▄
░▀▀░';;
4)char='
░█░█
░░▀█
░░░▀';;
5)char='
░█▀▀
░▀▀▄
░▀▀░';;
6)char='
░▄▀▀
░█▀▄
░░▀░';;
7)char='
░▀▀█
░▄▀░
░▀░░';;
8)char='
░▄▀▄
░▄▀▄
░░▀░';;
9)char='
░▄▀▄
░░▀█
░▀▀░';;
0)char='
░▄▀▄
░█/█
░░▀░';;
.)char='
░░░
░░░
░▀░';;
,)char='
░░░░
░░░░
░▄▀░';;
*)char='
░░
░░
░░';;

    esac
    for line in $char; do
        printf $line
        printf "\033[1B\033[${#line}D"
    done
    # printf "\033[3A\033[4C"
    printf "\033[3A\033[${#line}C"
done
printf "\033[2B\r"
}

printf "$(embtoilet "$distro")
host:		$host
kernel:		$kernel
uptime:		$uptime
pkgs:		$pkgs
shell:		$shell
disp:		$disp
term:		$term
cpu:		$cpu
ram:		$ram
battery:	$battery
locale:		$locale
"


