#!/bin/sh
# ShiTTY FETCH & busybox and POSIX compliant
# this file is licensed under the LGPLv2.
# this file was not made by any AI

# i dont know why, but i think a simple fetch shouldn't be so
# over complicated.

# thanks to:
# dylanaraps for the pure-sh-bible
# neofetch for the logos

# * [JUMP TO ACTUAL FETCH PRINT](#SHPRINT)

supercoolhelp(){
printf "%s" "\
ShiTTY FETCH, a very poopy fetch 💩
usage: shfetch

optional arguments
-h --help		displays this help.
-d --distro		overwrites distribution name
-V --variables		displays help for variables in the script.
--debug	 		enables debugging (prints everything even if empty).
-t --toilet		uses \`toilet -f pagga\` to print the distribution name (can't be spaced).
-C --right [num] 	spaces the table to the right a given number of spaces.
-s --sep [num] 		sets the separation between data:______value

"
exit 0
}
variablehelp(){
printf "%s" "\
colors and others are overwritten if you define them in your enviroment.

c0= 			table _name:_ color
c1= 			table _value_ color
c2= 			embtoilet color
c3=	 		distribution logo color
c[4-undef]=	 	distribution logo color
separ= separation length between name:______value
space= space from the 1st wall (tweak it to undesrtand it)

example:
c1=\"\\033[10;34m\" space=42 separ=13 shfetch
"
exit 0
}

while [ $# -gt 0 ] ; do
    case $1 in
        -h | --h*)  supercoolhelp ;;
        -d | --distro) distro=$2 ; shift 2;;
        -V | --var*) variablehelp ;;
        --debug) debug=1 ; shift ;;
        -C | --right) space=${2} ; shift 2 ;;
        -s | --sep*) separ=${2} ; shift 2 ;;
        *) printf "ermmmmm, idk what you're talking about,\nyour arguments are kinda strange.\n" ; shift ; exit 2 ;;
    esac
done
separ=${separ:-16}

# values initialization
# --------------------
if [ -z "$distro" ] ; then
distro=$(grep ^PRETTY_NAME /etc/os-release)
	# remove from left(##) 		  ; remove from right(%%)
	# keep one \", for parsing only the distro name to embtoilet
    distro=${distro#PRETTY_NAME=}; distro=${distro%\'}
fi
[ -e /sys/devices/virtual/dmi/id/product_name ] && host=$(cat /sys/devices/virtual/dmi/id/product_name)
kernel=$(uname -r)
uptime=$(uptime)
    uptime=${uptime%%user*} ; uptime=${uptime%,*} ; uptime=${uptime##*"up "} ; uptime=$(echo $uptime | sed  's/:/h/')
# pkgs and colors
    case "$distro" in
       *Gentoo*) pkgs="$(qlist -I | wc -l) (emerge)" ; space=${space:-37}
       c0=${c0:-"\033[10;35m"} ; c1=${c1:-"\033[10;95m"} ; c2=${c2:-"\033[10;37m"}
       c3=${c3:-"\033[35;1m"} ; c4=${c4:-"\033[37;1m"} ;;
       # comment: gnu `grep` is much faster than busybox `grep`
       *Alpine*) pkgs="$(grep ^C:Q /lib/apk/db/installed | wc -l) (apk)" ; space=${space:-42} ;
       c0=${c0:-"\033[2;34m"} ; c1=${c1:-"\033[2;36m"} ; c3=${c3:-"\033[10;36m"} ;;
       *) pkgs="9999 (not found)" ; space=${space:-32} ;;
    esac
clr="\033[0m"

shell=$SHELL
disp=${WAYLAND_DISPLAY%%-*}
    # Check if its xorg
    if [ -z "$disp" ] && [ "$DISPLAY" = ":0" ]; then disp="xorg" ; fi ;
term=$TERM
cpu="$(grep -m 1 '^model name' /proc/cpuinfo )" ; cpu=${cpu#*:}; [ -z "$cpu" ] && cpu="$(arch)"
				     # delete  kB	     delete spaces and name
tram=$(grep ^MemTotal: /proc/meminfo) ; tram=${tram%\ *} ; tram=${tram##"MemTotal:"*\ }
fram=$(grep ^MemAvailable:  /proc/meminfo) ; fram=${fram%\ *} ; fram=${fram##"MemAvailable:"*\ }
    tram=$(echo "scale=2 ;$tram/1024/1024" | bc -s)
    fram=$(echo "scale=2 ;$fram/1024/1024" | bc -s)     ; uram=$(echo "scale=2 ;$tram-$fram" | bc -s)
    ram="$uram/${tram}GiB"
    unset tram fram uramright
[ -d "/sys/class/power_supply/BAT0" ] && battery="$(cat /sys/class/power_supply/BAT0/capacity)%% [$(cat /sys/class/power_supply/BAT0/status)]"
locale=$LANG
# --------------------


embtoilet() {
# no comments, new lines and stdin cutted for space efficiency
# see https://codeberg.org/melspowr/embtoilet for full version
distro=$1; distro=$(printf "$distro" | tr 'A-Z' 'a-z') ; printf "\n\n\n" ; printf "\033[3A\033[${space}C"
while [ ${#distro} -ne 0 ] ; do i=$(printf "%.1s" "$distro" ) ; distro=${distro#${i}}
case $i in
a)char="░█▀█ ░█▀█ ░▀░▀";;
b)char="░█▀▄ ░█▀▄ ░▀▀░";;
c)char="░█▀▀ ░█░░ ░▀▀▀";;
d)char="░█▀▄ ░█░█ ░▀▀░";;
e)char="░█▀▀ ░█▀▀ ░▀▀▀";;
f)char="░█▀▀ ░█▀▀ ░▀░░";;
g)char="░█▀▀ ░█░█ ░▀▀▀";;
h)char="░█░█ ░█▀█ ░▀░▀";;
i)char="░▀█▀ ░░█░ ░▀▀▀";;
j)char="░▀▀█ ░░░█ ░▀▀░";;
k)char="░█░█ ░█▀▄ ░▀░▀";;
l)char="░█░░ ░█░░ ░▀▀▀";;
m)char="░█▄█ ░█░█ ░▀░▀";;
n)char="░█▀█ ░█░█ ░▀░▀";;
o)char="░█▀█ ░█░█ ░▀▀▀";;
p)char="░█▀█ ░█▀▀ ░▀░░";;
q)char="░▄▀▄ ░█\\█ ░░▀\\";;
r)char="░█▀▄ ░█▀▄ ░▀░▀";;
s)char="░█▀▀ ░▀▀█ ░▀▀▀";;
t)char="░▀█▀ ░░█░ ░░▀░";;
u)char="░█░█ ░█░█ ░▀▀▀";;
v)char="░█░█ ░▀▄▀ ░░▀░";;
w)char="░█░█ ░█▄█ ░▀░▀";;
x)char="░█░█ ░▄▀▄ ░▀░▀";;
y)char="░█░█ ░░█░ ░░▀░";;
z)char="░▀▀█ ░▄▀░ ░▀▀▀";;
1)char="░▀█░ ░░█░ ░▀▀▀";;
2)char="░▀▀▄ ░▄▀░ ░▀▀▀";;
3)char="░▀▀█ ░░▀▄ ░▀▀░";;
4)char="░█░█ ░░▀█ ░░░▀";;
5)char="░█▀▀ ░▀▀▄ ░▀▀░";;
6)char="░▄▀▀ ░█▀▄ ░░▀░";;
7)char="░▀▀█ ░▄▀░ ░▀░░";;
8)char="░▄▀▄ ░▄▀▄ ░░▀░";;
9)char="░▄▀▄ ░░▀█ ░▀▀░";;
0)char="░▄▀▄ ░█/█ ░░▀░";;
.)char="░░░ ░░░ ░▀░";;
,)char="░░░░ ░░░░ ░▄▀░";;
*)char="░░ ░░ ░░";;
esac
for line in $char ; do printf $line ; printf "\033[1B\033[${#line}D" ; done
printf "\033[3A\033[${#line}C"
done ; printf "\033[3B\r"
}

case "$distro" in 
*Gentoo*)logo="\
${c3}         -/oyddmdhs+:.
     -o${c4}dNMMMMMMMMNNmhy+${c3}-\`
   -y${c4}NMMMMMMMMMMMNNNmmdhy${c3}+-
 \`o${c4}mMMMMMMMMMMMMNmdmmmmddhhy${c3}/\`
 om${c4}MMMMMMMMMMMN${c3}hhyyyo${c4}hmdddhhhd${c3}o\`
.y${c4}dMMMMMMMMMMd${c3}hs++so/s${c4}mdddhhhhdm${c3}+\`
 oy${c4}hdmNMMMMMMMN${c3}dyooy${c4}dmddddhhhhyhN${c3}d.
  :o${c4}yhhdNNMMMMMMMNNNmmdddhhhhhyym${c3}Mh
    .:${c4}+sydNMMMMMNNNmmmdddhhhhhhmM${c3}my
       /m${c4}MMMMMMNNNmmmdddhhhhhmMNh${c3}s:
    \`o${c4}NMMMMMMMNNNmmmddddhhdmMNhs${c3}+\`
  \`s${c4}NMMMMMMMMNNNmmmdddddmNMmhs${c3}/.
 /N${c4}MMMMMMMMNNNNmmmdddmNMNdso${c3}:\`
+M${c4}MMMMMMNNNNNmmmmdmNMNdso${c3}/-
yM${c4}MNNNNNNNmmmmmNNMmhs+/${c3}-\`
/h${c4}MMNNNNNNNNMNdhs++/${c3}-\`
\`/${c4}ohdmmddhys+++/:${c3}.\`
  \`-//////:--.
";;
*Alpine*)logo="\
${c3}       .hddddddddddddddddddddddh.
      :dddddddddddddddddddddddddd:
     /dddddddddddddddddddddddddddd/
    +dddddddddddddddddddddddddddddd+
  \`sdddddddddddddddddddddddddddddddds\`
 \`ydddddddddddd++hdddddddddddddddddddy\`
.hddddddddddd+\`  \`+ddddh:-sdddddddddddh.
hdddddddddd+\`      \`+y:    .sddddddddddh
ddddddddh+\`   \`//\`   \`.\`     -sddddddddd
ddddddh+\`   \`/hddh/\`   \`:s-    -sddddddd
ddddh+\`   \`/+/dddddh/\`   \`+s-    -sddddd
ddd+\`   \`/o\` :dddddddh/\`   \`oy-    .yddd
hdddyo+ohddyosdddddddddho+oydddy++ohdddh
.hddddddddddddddddddddddddddddddddddddh.
 \`yddddddddddddddddddddddddddddddddddy\`
  \`sdddddddddddddddddddddddddddddddds\`
    +dddddddddddddddddddddddddddddd+
     /dddddddddddddddddddddddddddd/
      :dddddddddddddddddddddddddd:
       .hddddddddddddddddddddddh.
";;


# from https://www.twitchquotes.com/copypastas/689
*)logo="\
░░░░░▄▄▄▄▀▀▀▀▀▀▀▀▄▄▄▄▄▄░░░░░░░
░░░░░█░░░░▒▒▒▒▒▒▒▒▒▒▒▒░░▀▀▄░░░░
░░░░█░░░▒▒▒▒▒▒░░░░░░░░▒▒▒░░█░░░
░░░█░░░░░░▄██▀▄▄░░░░░▄▄▄░░░░█░░
░▄▀▒▄▄▄▒░█▀▀▀▀▄▄█░░░██▄▄█░░░░█░
█░▒█▒▄░▀▄▄▄▀░░░░░░░░█░░░▒▒▒▒▒░█
█░▒█░█▀▄▄░░░░░█▀░░░░▀▄░░▄▀▀▀▄▒█
░█░▀▄░█▄░█▀▄▄░▀░▀▀░▄▄▀░░░░█░░█░
░░█░░░▀▄▀█▄▄░█▀▀▀▄▄▄▄▀▀█▀██░█░░
░░░█░░░░██░░▀█▄▄▄█▄▄█▄████░█░░░
░░░░█░░░░▀▀▄░█░░░█░█▀██████░█░░
░░░░░▀▄░░░░░▀▀▄▄▄█▄█▄█▄█▄▀░░█░░
░░░░░░░▀▄▄░▒▒▒▒░░░░░░░░░░▒░░░█░
░░░░░░░░░░▀▀▄▄░▒▒▒▒▒▒▒▒▒▒░░░░█░
░░░░░░░░░░░░░░▀▄▄▄▄▄░░░░░░░░█░░
"; space=${space:-32};;
esac
lheight=$(printf "$logo" | wc -l)

#SHPRINT
## table build
## -----------
 toilet="$(embtoilet "${distro#*\'}")"
   host="host:           $host"
 kernel="kernel:         $kernel"
 uptime="uptime:         $uptime"
   pkgs="pkgs:           $pkgs"
  shell="shell:          $shell"
   disp="disp:           $disp"
   term="term:           $term"
    cpu="cpu:            $cpu"
    ram="ram:            $ram"
battery="battery:        $battery"
 locale="locale:         $locale"
# --------------------

# print the logo and bring the cursor back
printf "$logo${clr}\033[${lheight}A"
# print the toilet text
printf "${c2}$toilet${clr}"
theight=0
for line in  "$host" "$kernel" "$uptime" "$pkgs" "$shell" "$disp" "$term" "$cpu" "$ram" "$battery" "$locale" ; do
    theight=$(($theight+1))
    set $line
   	    # from  https://github.com/dylanaraps/pure-sh-bible#conditional-expressions
   	    # honestly idk why it works
    if [ ! -z "${2#${2%%[![:space:]]*}}" ] || [ $debug ]; then
        printf "\033[${space}C${c0}$1${clr}\033[${#1}D" ; shift
        printf "\033[${separ}C${c1}$*${clr}\n"
    fi
done
printf "\033[$(($lheight - $theight - 3))B"
